#!/bin/sh
# File generated by ocamlbuild

cd /Users/dodo/ocaml_projects/pyml/ocaml/_build

rm -f pyml.cmi
rm -f pyml.cmo
rm -f pyml.cmx
rm -f pyml.ml.depends
rm -f pyml.o
rm -f pyml_test.cmi
rm -f pyml_test.cmo
rm -f pyml_test.cmx
rm -f pyml_test.ml.depends
rm -f pyml_test.o
# Also clean the script itself
rm -f /Users/dodo/ocaml_projects/pyml/ocaml/_build/_build/sanitize.sh
