#!/bin/sh
# File generated by ocamlbuild

cd /Users/dodo/ocaml_projects/pyml

rm -f pyml.cmi
rm -f pyml.cmx
rm -f pyml.o
# Also clean the script itself
rm -f /Users/dodo/ocaml_projects/pyml/_build/sanitize.sh
